# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'YelpImageSearch' do
  pod 'Alamofire', '~> 4.5'
  pod 'SwiftKeychainWrapper'
end
